namespace LightDancing.Enums
{
    public enum AnimationShaders
    {
        ShiftColors,
        StillColors,
    }

    public enum BackgroundShaders
    {
        HalfCircle,
        Fire,
        FadeCircle,
        Diamond,
        HalfRainbow,
        Flowers,
        Triangle,
        ClappingBall,
        Rectangle,
        RoundCircle,
        Arrow,
        Grid,
        StripRotate,
        GridRotate,
        Squares,
        //Cartoon
        CartoonBG1,
        CartoonBG2,
        CartoonBG3,
        CartoonBG4,
        CartoonBG5,
        CartoonBG6,
        CartoonBG7,
        //PopArt
        MovingDots,
        PAHorizontalStrip,
        VerticalStrip,
        MovingSlope,
        MovingTriangleWave,
        MovingDotLarge,
        //Geo
        CircleSquare,
        GeoSquare,
        GeoSquare2,
        GeoSquare3,
        GeoSquare4,
        GeoSquare5,
        GeoSquare6,
        GeoSquare7,
        GeoSquare8,
        RotateGeo,
        GeoCircle,
        Hexagon,
        GeoLines,
        GeoLines2,
        GeoLines3,
        GeoLines4,
        //Kale
        Kale1,
        Kale2,
        Kale3,
        Kale4,
        Kale5,
        Kale6,
        Kale7,
        Kale8,
        Kale9,
        Kale10,
        Kale11,
        Kale12,
        //Trip
        AlienFlower,
        AlienShip,
        AlienFlower2,
        BottleRainbow,
        CheckboardFire,
        FadeAlien,
        FlowerShape,
        Hamburger,
        Pacman,
        MeltSmile,
        Monster,
        //New Music Analysis
        BackgroundBar,
    }

    public enum PanoramaShaders
    {
        Heart,
        HorizontalStrip,
        SpotLights,
        HeadLights,
        DiamondLights,
        CircleSquare,
        Wave,
        Ripple,
        RotateCircle,
        RotateDiamond,
        LineRotate,
        HorizontalLines,
        CrossLines,
        TriangleLine,
        Swirl,
        //Cartoon
        CartoonPanorama1,
        CartoonPanorama2,
        CartoonPanorama3,
        CartoonPanorama4,
        CartoonPanorama5,
        //PopArt
        FourSquare,
        DotSquare,
        CornerDot,
        CornerTriangleWave,
        //Geo
        MidCircleSquare,
        MidGeoCircle,
        MidGeoLines,
        MidGeoLines2,
        MidGeoLines3,
        MidGeoLines4,
        MidGeoSquare,
        MidGeoSquare2,
        MidGeoSquare3,
        MidGeoSquare4,
        MidGeoSquare5,
        MidGeoSquare6,
        MidGeoSquare7,
        MidGeoSquare8,
        MidHexagon,
        MidRotateGeo,
        //New Music Analysis
        PanoramaBar,
    }

    public enum ProtagonistShaders
    {
        BouncingBall,
        RadiusLaser,
        Laser,
        RandomString,
        Rain,
        StillBalls,
        RandomCross,
        RandomHeart,
        RandomTarget,
        RandomTree,
        SquareWave,
        //Cartoon
        CartoonProtagonist1,
        CartoonProtagonist2,
        CartoonProtagonist3,
        CartoonProtagonist4,
        CartoonProtagonist5,
        CartoonProtagonist6,
        //PopArt
        TSquare,
        OSquare,
        RandomCurve,
        TwoSideCircle,
        RandomCircle,
        RandomRect,
        //Geo
        HighCircleSquare,
        HighGeoSquare,
        HighGeoSquare2,
        HighGeoSquare3,
        HighGeoSquare4,
        HighGeoSquare5,
        HighGeoSquare6,
        HighGeoSquare7,
        HighGeoSquare8,
        HighRotateGeo,
        HighGeoCircle,
        HighHexagon,
        HighGeoLines,
        HighGeoLines2,
        HighGeoLines3,
        HighGeoLines4,
        //New Music Analysis
        ProtagonistBar,
    }

    public enum KickDrumShaders
    {
        KickBar,
    }

    public enum MusicAnimateShaders
    {
        CircleWave_2,
        CircleRamp,
        ColorRotate,
    }

    public enum WallpaperAnimateShaders
    {
        ColorShift,
        ColorSwirl,
        ColorBounceBall,
        HalfColorCircle,
        MixColor,
        ColorStrip,
        FluidGrid,
        MeltingSmileFace,
        ColorRings,
        CheckboardFluid,
        FixColorRotate,
    }
}
